server:
  port: 8888
  tomcat:
    max-threads: 500

spring:
  redis:
    host: 172.21.23.56
    port: 6379
    jedis:
      pool:
        max-active: 8
  mvc:
    servlet:
      load-on-startup: 1
demo:
  properties:
#    person-name: 测试1
    personName: 测试2
  server:
    port: 8989